Updated current maintainers and our team page
etn-ccis/blui-doc-it pull request #677
Opened 2023-05-22 19:04 UTC by yazadsidhwa-eaton

Fixes # .

#### Changes proposed in this Pull Request:

- Added in Ragha, Manoj, and Yazad to Current Maintainers on Landing Page
- Updated the Our Team page with information from Yazad (still waiting to update for Ragha and Manoj)

#### Screenshots / Screen Recording (if applicable)

-

#### To Test:

-

#### Any specific feedback you are looking for?

-

2023-06-01 20:10 UTC, huayunh requested changes

2023-06-01 20:10 UTC, huayunh commented on src/__configuration__/contributors/currentMaintainers.ts
> +            'He loves to code both frontend & backend to create beautiful performant products with delightful user experiences. He has a passion for learning and exploring new things, especially in t
I recommend running this through a grammar checker

2023-06-01 20:10 UTC, huayunh commented on src/__configuration__/contributors/currentMaintainers.ts
> +            linkedIn: 'https://github.com/RaghavendranC-Eaton',
why is there a GitHub link in the linkedIn field?

2023-06-02 14:43 UTC, huayunh approved these changes

2023-06-02 16:40 UTC, JeffGreiner-eaton commented on src/__configuration__/contributors/currentMaintainers.ts
> +            'Software developer who primarily works on the front-end technologies. His hobbies are playing cricket, travelling, listening to music and watching movies.',
one "L" in traveling for US but ok in UK

2023-06-02 16:44 UTC, JeffGreiner-eaton commented
Also for some reason we lost our mobile view from your previous PR
Currently it looks like this in this PR...

![image](https://github.com/etn-ccis/blui-doc-it/assets/119693939/0b32f934-dac6-473a-a60f-e3c8e4a64016)

2023-06-02 18:42 UTC, merged

2023-06-02 18:42 UTC, yazadsidhwa-eaton commented
Mobile view should be fixed automatically when this branch is merged with Dev